#!/usr/bin/env bash

# exit on non 0 status code
set -e

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing sudo time stamp until the script has finished.
# This runs a harmless command in the background every 60 seconds.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done &

echo "Updating sources.list..."
# need "contrib" and "non-free" in sources.list
sudo sed -i 's/ main$/ main contrib non-free/' /etc/apt/sources.list

sudo apt install linux-headers-$(uname -r)